### ISSUE TITLE
Error: Cannot find module 'ajv/dist/compile/codegen'

### ISSUE THREAD

**Issue by Hongbo-Miao** [Hongbo-Miao/hongbomiao.com#6245]
https://github.com/Hongbo-Miao/hongbomiao.com/actions/runs/3616053247/jobs/6094918228

```sh
Run npm run build

> hm-panel-plugin@1.0.0 build
> webpack -c ./.config/webpack/webpack.config.ts --env production

[webpack-cli] Failed to load '/home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/.config/webpack/webpack.config.ts' config
[webpack-cli] Error: Cannot find module 'ajv/dist/compile/codegen'
Require stack:
- /home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/ajv-keywords/dist/definitions/typeof.js
- /home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/ajv-keywords/dist/keywords/typeof.js
- /home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/ajv-keywords/dist/keywords/index.js
- /home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/ajv-keywords/dist/index.js
- /home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/schema-utils/dist/validate.js
- /home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/schema-utils/dist/index.js
- /home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/copy-webpack-plugin/dist/index.js
- /home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/.config/webpack/webpack.config.ts
- /home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/webpack-cli/lib/webpack-cli.js
- /home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/webpack-cli/lib/bootstrap.js
- /home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/webpack-cli/bin/cli.js
- /home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:8[4](https://github.com/Hongbo-Miao/hongbomiao.com/actions/runs/3616053247/jobs/6094918152#step:7:5)1:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/ajv-keywords/src/definitions/typeof.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:11[5](https://github.com/Hongbo-Miao/hongbomiao.com/actions/runs/3616053247/jobs/6094918152#step:7:6)9:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .js] (/home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/ts-node/src/index.ts:1[6](https://github.com/Hongbo-Miao/hongbomiao.com/actions/runs/3616053247/jobs/6094918152#step:7:7)08:43)
    at Module.load (node:internal/modules/cjs/loader:103[7](https://github.com/Hongbo-Miao/hongbomiao.com/actions/runs/3616053247/jobs/6094918152#step:7:8):[32](https://github.com/Hongbo-Miao/hongbomiao.com/actions/runs/3616053247/jobs/6094918152#step:7:33)) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/ajv-keywords/dist/definitions/typeof.js',
    '/home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/ajv-keywords/dist/keywords/typeof.js',
    '/home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/ajv-keywords/dist/keywords/index.js',
    '/home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/ajv-keywords/dist/index.js',
    '/home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/schema-utils/dist/validate.js',
    '/home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/schema-utils/dist/index.js',
    '/home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/copy-webpack-plugin/dist/index.js',
    '/home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/.config/webpack/webpack.config.ts',
    '/home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/webpack-cli/lib/webpack-cli.js',
    '/home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/webpack-cli/lib/bootstrap.js',
    '/home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/webpack-cli/bin/cli.js',
    '/home/runner/work/hongbomiao.com/hongbomiao.com/grafana/hm-panel-plugin/node_modules/webpack/bin/webpack.js'
  ]
}
Error: Process completed with exit code 2.
```

**Comment by Hongbo-Miao** [comment]
Tried clean cache, which does not help.
Tried to reproduce on macOS by cloning a clean repo and `npm ci && npm run build`, but still failed to reproduce.
Ended up by adding `ajv` in `devDependencies`.
