### ISSUE TITLE
java.nio.file.NoSuchFileException: xxx/hadoop-client-api-3.3.4.jar

### ISSUE THREAD

**Issue by Hongbo-Miao** [Hongbo-Miao/hongbomiao.com#8135]
When I run `sbt run` for a Spark application, I got error

> java.nio.file.NoSuchFileException: xxx/hadoop-client-api-3.3.4.jar

<details>
  <summary>Full log</summary>
  
  ```shell
  sbt run
  [info] welcome to sbt 1.8.2 (Homebrew Java 17.0.6)
  [info] loading project definition from hongbomiao.com/hm-spark/applications/find-retired-people-scala/project
  
    | => find-retired-people-scala-build / Compile / compileIncremental 0s
  [info] loading settings for project find-retired-people-scala from build.sbt ...
  [info] set current project to FindRetiredPeople (in build file:hongbomiao.com/hm-spark/applications/find-retired-people-scala/)
  
    | => find-retired-people-scala / update 0s
  
    | => find-retired-people-scala / Compile / compileIncremental 0s
  
    | => find-retired-people-scala / Compile / compileIncremental 0s
  [info] running com.hongbomiao.FindRetiredPeople 
  Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
  23/04/19 16:28:22 WARN Utils: Your hostname, Hongbos-MacBook-Pro-2021.local resolves to a loopback address: 127.0.0.1; using 10.10.8.223 instead (on interface en0)
  23/04/19 16:28:22 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
  23/04/19 16:28:22 INFO SparkContext: Running Spark version 3.4.0
  23/04/19 16:28:22 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
  23/04/19 16:28:22 INFO ResourceUtils: ==============================================================
  23/04/19 16:28:22 INFO ResourceUtils: No custom resources configured for spark.driver.
  23/04/19 16:28:22 INFO ResourceUtils: ==============================================================
  23/04/19 16:28:22 INFO SparkContext: Submitted application: find-retired-people-scala
  23/04/19 16:28:22 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
  23/04/19 16:28:22 INFO ResourceProfile: Limiting resource is cpu
  23/04/19 16:28:22 INFO ResourceProfileManager: Added ResourceProfile id: 0
  23/04/19 16:28:22 INFO SecurityManager: Changing view acls to: hongbo-miao
  23/04/19 16:28:22 INFO SecurityManager: Changing modify acls to: hongbo-miao
  23/04/19 16:28:22 INFO SecurityManager: Changing view acls groups to: 
  23/04/19 16:28:22 INFO SecurityManager: Changing modify acls groups to: 
  23/04/19 16:28:22 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: hongbo-miao; groups with view permissions: EMPTY; users with modify permissions: hongbo-miao; groups with modify permissions: EMPTY
  23/04/19 16:28:22 INFO Utils: Successfully started service 'sparkDriver' on port 64550.
  23/04/19 16:28:22 INFO SparkEnv: Registering MapOutputTracker
  23/04/19 16:28:22 INFO SparkEnv: Registering BlockManagerMaster
  23/04/19 16:28:22 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
  23/04/19 16:28:22 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
  23/04/19 16:28:22 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
  23/04/19 16:28:22 INFO DiskBlockManager: Created local directory at /private/var/folders/22/ntjwd5dx691gvkktkspl0f_00000gq/T/blockmgr-484c32c3-42df-4bb0-bfb6-93bca8799dab
  23/04/19 16:28:22 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
  23/04/19 16:28:22 INFO SparkEnv: Registering OutputCommitCoordinator
  23/04/19 16:28:22 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
  23/04/19 16:28:22 INFO Utils: Successfully started service 'SparkUI' on port 4040.
  23/04/19 16:28:22 INFO Executor: Starting executor ID driver on host 10.10.8.223
  23/04/19 16:28:22 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
  23/04/19 16:28:22 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 64552.
  23/04/19 16:28:22 INFO NettyBlockTransferService: Server created on 10.10.8.223:64552
  23/04/19 16:28:22 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
  23/04/19 16:28:22 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.10.8.223, 64552, None)
  23/04/19 16:28:22 INFO BlockManagerMasterEndpoint: Registering block manager 10.10.8.223:64552 with 434.4 MiB RAM, BlockManagerId(driver, 10.10.8.223, 64552, None)
  23/04/19 16:28:22 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.10.8.223, 64552, None)
  23/04/19 16:28:22 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 10.10.8.223, 64552, None)
  23/04/19 16:28:23 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
  23/04/19 16:28:23 INFO SharedState: Warehouse path is 'file:hongbomiao.com/hm-spark/applications/find-retired-people-scala/spark-warehouse'.
  23/04/19 16:28:24 INFO CodeGenerator: Code generated in 120.900875 ms
  23/04/19 16:28:24 INFO CodeGenerator: Code generated in 5.882833 ms
  23/04/19 16:28:24 INFO CodeGenerator: Code generated in 4.50325 ms
  23/04/19 16:28:24 INFO CodeGenerator: Code generated in 6.235417 ms
  23/04/19 16:28:24 INFO SparkContext: SparkContext is stopping with exitCode 0.
  23/04/19 16:28:24 INFO SparkUI: Stopped Spark web UI at http://10.10.8.223:4040
  +-------+---+
  |   name|age|
  +-------+---+
  |Charlie| 80|
  +-------+---+
  
  23/04/19 16:28:24 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
  23/04/19 16:28:24 INFO MemoryStore: MemoryStore cleared
  23/04/19 16:28:24 INFO BlockManager: BlockManager stopped
  23/04/19 16:28:24 INFO BlockManagerMaster: BlockManagerMaster stopped
  23/04/19 16:28:24 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
  23/04/19 16:28:24 INFO SparkContext: Successfully stopped SparkContext
  [success] Total time: 7 s, completed Apr 19, 2023, 4:28:24 PM
  23/04/19 16:28:25 INFO ShutdownHookManager: Shutdown hook called
  23/04/19 16:28:25 INFO ShutdownHookManager: Deleting directory /private/var/folders/22/ntjwd5dx691gvkktkspl0f_00000gq/T/spark-5e9a60e6-2699-4353-95cb-a93a87b70f63
  23/04/19 16:28:25 ERROR Configuration: error parsing conf core-default.xml
  java.nio.file.NoSuchFileException: hongbomiao.com/hm-spark/applications/find-retired-people-scala/target/bg-jobs/sbt_17e38c6e/target/f5c922ec/359669fc/hadoop-client-api-3.3.4.jar
	  at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	  at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	  at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	  at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	  at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
	  at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	  at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
	  at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	  at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	  at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	  at java.base/java.util.jar.JarFile.<init>(JarFile.java:347)
	  at java.base/sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:103)
	  at java.base/sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:72)
	  at java.base/sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:168)
	  at java.base/sun.net.www.protocol.jar.JarFileFactory.getOrCreate(JarFileFactory.java:91)
	  at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:132)
	  at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:175)
	  at org.apache.hadoop.conf.Configuration.parse(Configuration.java:3009)
	  at org.apache.hadoop.conf.Configuration.getStreamReader(Configuration.java:3105)
	  at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3063)
	  at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:3036)
	  at org.apache.hadoop.conf.Configuration.loadProps(Configuration.java:2914)
	  at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2896)
	  at org.apache.hadoop.conf.Configuration.get(Configuration.java:1246)
	  at org.apache.hadoop.conf.Configuration.getTimeDuration(Configuration.java:1863)
	  at org.apache.hadoop.conf.Configuration.getTimeDuration(Configuration.java:1840)
	  at org.apache.hadoop.util.ShutdownHookManager.getShutdownTimeout(ShutdownHookManager.java:183)
	  at org.apache.hadoop.util.ShutdownHookManager.shutdownExecutor(ShutdownHookManager.java:145)
	  at org.apache.hadoop.util.ShutdownHookManager.access$300(ShutdownHookManager.java:65)
	  at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:102)
  Exception in thread "Thread-1" java.lang.RuntimeException: java.nio.file.NoSuchFileException: hongbomiao.com/hm-spark/applications/find-retired-people-scala/target/bg-jobs/sbt_17e38c6e/target/f5c922ec/359669fc/hadoop-client-api-3.3.4.jar
	  at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3089)
	  at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:3036)
	  at org.apache.hadoop.conf.Configuration.loadProps(Configuration.java:2914)
	  at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2896)
	  at org.apache.hadoop.conf.Configuration.get(Configuration.java:1246)
	  at org.apache.hadoop.conf.Configuration.getTimeDuration(Configuration.java:1863)
	  at org.apache.hadoop.conf.Configuration.getTimeDuration(Configuration.java:1840)
	  at org.apache.hadoop.util.ShutdownHookManager.getShutdownTimeout(ShutdownHookManager.java:183)
	  at org.apache.hadoop.util.ShutdownHookManager.shutdownExecutor(ShutdownHookManager.java:145)
	  at org.apache.hadoop.util.ShutdownHookManager.access$300(ShutdownHookManager.java:65)
	  at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:102)
  Caused by: java.nio.file.NoSuchFileException: hongbomiao.com/hm-spark/applications/find-retired-people-scala/target/bg-jobs/sbt_17e38c6e/target/f5c922ec/359669fc/hadoop-client-api-3.3.4.jar
	  at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	  at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	  at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	  at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	  at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
	  at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	  at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
	  at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	  at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	  at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	  at java.base/java.util.jar.JarFile.<init>(JarFile.java:347)
	  at java.base/sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:103)
	  at java.base/sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:72)
	  at java.base/sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:168)
	  at java.base/sun.net.www.protocol.jar.JarFileFactory.getOrCreate(JarFileFactory.java:91)
	  at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:132)
	  at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:175)
	  at org.apache.hadoop.conf.Configuration.parse(Configuration.java:3009)
	  at org.apache.hadoop.conf.Configuration.getStreamReader(Configuration.java:3105)
	  at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3063)
	  ... 10 more
  
  Process finished with exit code 0
  ```
</details>

**Comment by Hongbo-Miao** [comment]
Some potential helpful info

- https://github.com/sbt/sbt/issues/6888
